version: 1.0.2
name: bytebot

services:
  bytebot-desktop:
    image: ghcr.io/bytebot-ai/bytebot-desktop:edge
    shm_size: "2g"
    container_name: bytebot-desktop
    restart: unless-stopped
    hostname: computer
    privileged: true
    ports:
      - "9990:9990"
    environment:
      - DISPLAY=:0
    networks:
      - bytebot-network

  postgres:
    image: postgres:16-alpine
    container_name: bytebot-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bytebotdb
    networks:
      - bytebot-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bytebot-agent:
    image: ghcr.io/bytebot-ai/bytebot-agent:edge
    container_name: bytebot-agent
    restart: unless-stopped
    ports:
      - "9991:9991"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/bytebotdb}
      - BYTEBOT_DESKTOP_BASE_URL=${BYTEBOT_DESKTOP_BASE_URL:-http://bytebot-desktop:9990}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
    networks:
      - bytebot-network

  bytebot-ui:
    image: ghcr.io/bytebot-ai/bytebot-ui:edge
    container_name: bytebot-ui
    restart: unless-stopped
    ports:
      - "9992:9992"
    environment:
      - NODE_ENV=production
      - BYTEBOT_AGENT_BASE_URL=${BYTEBOT_AGENT_BASE_URL:-http://bytebot-agent:9991}
      - BYTEBOT_DESKTOP_VNC_URL=${BYTEBOT_DESKTOP_VNC_URL:-http://bytebot-desktop:9990/websockify}
    depends_on:
      - bytebot-agent
    networks:
      - bytebot-network
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"
      
      # Define the router
      - "traefik.http.routers.bytebot-ui.rule=Host(`${COOLIFY_FQDN}`)"
      - "traefik.http.routers.bytebot-ui.entrypoints=websecure"
      - "traefik.http.routers.bytebot-ui.tls.certresolver=letsencrypt"
      
      # Define the service and port
      - "traefik.http.services.bytebot-ui.loadbalancer.server.port=9992"
      
      # Apply basic auth middleware
      - "traefik.http.routers.bytebot-ui.middlewares=bytebot-auth"
      
      # Define basic auth middleware with correct credentials
      - "traefik.http.middlewares.bytebot-auth.basicauth.users=rotz:$$apr1$$35EuGfDk$$SfxgSmwiNrfgody09SPZd/"

networks:
  bytebot-network:
    driver: bridge

volumes:
  postgres_data:
