name: Sync with Upstream

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/bytebot-ai/bytebot.git || true
          git fetch upstream

      - name: Backup our custom docker-compose.yml
        run: |
          cp docker/docker-compose.yml docker/docker-compose.yml.backup

      - name: Merge upstream changes
        run: |
          git merge upstream/main --no-edit || true

      - name: Restore our custom docker-compose.yml
        run: |
          cp docker/docker-compose.yml.backup docker/docker-compose.yml
          rm docker/docker-compose.yml.backup

      - name: Commit and push if there are changes
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Sync with upstream while preserving custom docker-compose.yml"
            git push origin main
          else
            echo "No changes to commit"
          fi

